<a href="https://colab.research.google.com/github/AayushA10/BASIC-CALCULATOR-USING-PHP/blob/main/DS_BOOTCAMP_WEEK_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
A = np.array([1, 2, 3, 4, 5])
B = np.array([6, 7, 8, 9, 10])

vertical_stack = np.vstack((A, B))
print("Vertical Stack:\n", vertical_stack)

horizontal_stack = np.hstack((A, B))
print("Horizontal Stack:\n", horizontal_stack)


Vertical Stack:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Horizontal Stack:
 [ 1  2  3  4  5  6  7  8  9 10]


In [2]:
common_elements = np.intersect1d(A, B)
print("Common Elements:", common_elements)

Common Elements: []


In [3]:
filtered_numbers = A[np.where((A >= 5) & (A <= 10))]
print("Numbers between 5 and 10:", filtered_numbers)

Numbers between 5 and 10: [5]


In [4]:

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0, 1, 2, 3])


filtered_iris = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]
print("Filtered Iris Data:\n", filtered_iris)


Filtered Iris Data:
 [[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


In [5]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

filtered_df = df[['Manufacturer', 'Model', 'Type']].iloc[::20]
print(filtered_df)


   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [8]:
import pandas as pd


df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')


df['Min.Price'] = df['Min.Price'].fillna(df['Min.Price'].mean())
df['Max.Price'] = df['Max.Price'].fillna(df['Max.Price'].mean())
print(df[['Min.Price', 'Max.Price']].isnull().sum())


Min.Price    0
Max.Price    0
dtype: int64


In [7]:

df_random = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

rows_with_sum_gt_100 = df_random[df_random.sum(axis=1) > 100]
print("Rows with row sum > 100:\n", rows_with_sum_gt_100)


Rows with row sum > 100:
      0   1   2   3
1   22  39  10  34
2   39  14  15  39
6   37  29  17  39
7   38  32  24  25
8   16  32  29  24
11  17  39  27  24
13  28  18  39  32
14  29  18  25  29
